// Comments API
const API_COMMENTS_URL = process.env.REACT_APP_COMMENT_API
const API_USERNAME = process.env.REACT_APP_API_USERNAME
const API_PASSWORD = process.env.REACT_APP_API_PASSWORD

// Movie API
const API_MOVIE_URL = process.env.REACT_APP_API_MOVIE_URL
const API_KEY = process.env.REACT_APP_API_MOVIE_KEY

export {
  API_COMMENTS_URL,
  API_USERNAME,
  API_PASSWORD,
  API_MOVIE_URL,
  API_KEY
}
